name: enough_convert
description: Support for character encodings / charsets / codecs missing from `dart:convert` - ISO 8859 / Latin, Windows, DOS, GBK, Big5, and KOI8 R/U, ISO-2022-JP.
version: 1.0.0
publish_to: 'none'
homepage: https://github.com/rascal-3/enough_convert

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  characters: ^1.0.0
  jcombu: ^1.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.5
